output=brightkite_statperc.txt  
python3 run.py --algorithm statperc --dataset brightkite         --numthread 96 --batch 1   -o p96_q1_cpu_statperc_brightkite.txt            &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 96 --batch 10  -o p96_q10_cpu_statperc_brightkite.txt           &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 96 --batch 40  -o p96_q40_cpu_statperc_brightkite.txt           &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 96 --batch 100 -o p96_q100_cpu_statperc_brightkite.txt          &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 64 --batch 1   -o p64_q1_cpu_statperc_brightkite.txt            &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 64 --batch 10  -o p64_q10_cpu_statperc_brightkite.txt           &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 64 --batch 40  -o p64_q40_cpu_statperc_brightkite.txt           &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 64 --batch 100 -o p64_q100_cpu_statperc_brightkite.txt          &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 48 --batch 1   -o p48_q1_cpu_statperc_brightkite.txt            &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 48 --batch 10  -o p48_q10_cpu_statperc_brightkite.txt           &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 48 --batch 40  -o p48_q40_cpu_statperc_brightkite.txt           &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 48 --batch 100 -o p48_q100_cpu_statperc_brightkite.txt          &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 32 --batch 1   -o p32_q1_cpu_statperc_brightkite.txt            &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 32 --batch 10  -o p32_q10_cpu_statperc_brightkite.txt           &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 32 --batch 40  -o p32_q40_cpu_statperc_brightkite.txt           &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 32 --batch 100 -o p32_q100_cpu_statperc_brightkite.txt          &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 16 --batch 1   -o p16_q1_cpu_statperc_brightkite.txt            &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 16 --batch 10  -o p16_q10_cpu_statperc_brightkite.txt           &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 16 --batch 40  -o p16_q40_cpu_statperc_brightkite.txt           &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 16 --batch 100 -o p16_q100_cpu_statperc_brightkite.txt          &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 8 --batch 1   -o p8_q1_cpu_statperc_brightkite.txt            &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 8 --batch 10  -o p8_q10_cpu_statperc_brightkite.txt           &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 8 --batch 40  -o p8_q40_cpu_statperc_brightkite.txt           &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 8 --batch 100 -o p8_q100_cpu_statperc_brightkite.txt          &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 4 --batch 1   -o p4_q1_cpu_statperc_brightkite.txt            &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 4 --batch 10  -o p4_q10_cpu_statperc_brightkite.txt           &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 4 --batch 40  -o p4_q40_cpu_statperc_brightkite.txt           &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 4 --batch 100 -o p4_q100_cpu_statperc_brightkite.txt          &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 2 --batch 1   -o p2_q1_cpu_statperc_brightkite.txt            &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 2 --batch 10  -o p2_q10_cpu_statperc_brightkite.txt           &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 2 --batch 40  -o p2_q40_cpu_statperc_brightkite.txt           &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 2 --batch 100 -o p2_q100_cpu_statperc_brightkite.txt          &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 1 --batch 1   -o p1_q1_cpu_statperc_brightkite.txt            &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 1 --batch 10  -o p1_q10_cpu_statperc_brightkite.txt           &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 1 --batch 40  -o p1_q40_cpu_statperc_brightkite.txt           &>> $output
python3 run.py --algorithm statperc --dataset brightkite         --numthread 1 --batch 100 -o p1_q100_cpu_statperc_brightkite.txt          &>> $output
