sh dynedge_brightkite.sh
sh dynperc_brightkite.sh
sh dynedge_slashdot.sh
sh dynperc_slashdot.sh
sh dynedge_p2p-Gnutella25.sh
sh dynperc_p2p-Gnutella25.sh
sh statedge_brightkite.sh
sh statperc_brightkite.sh
sh statedge_slashdot.sh
sh statperc_slashdot.sh
sh statedge_p2p-Gnutella25.sh
sh statperc_p2p-Gnutella25.sh